# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sbfc <- function(TrainX = NULL, TrainY = NULL, TestX = NULL, TestY = NULL) {
    .Call('sbfc_sbfc', PACKAGE = 'sbfc', TrainX, TrainY, TestX, TestY)
}

