// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sbfc
List sbfc(SEXP TrainX, SEXP TrainY, SEXP TestX, SEXP TestY, SEXP nstep, int thin, bool cv, bool thinoutputs);
RcppExport SEXP sbfc_sbfc(SEXP TrainXSEXP, SEXP TrainYSEXP, SEXP TestXSEXP, SEXP TestYSEXP, SEXP nstepSEXP, SEXP thinSEXP, SEXP cvSEXP, SEXP thinoutputsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type TrainX(TrainXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TrainY(TrainYSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TestX(TestXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TestY(TestYSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nstep(nstepSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< bool >::type cv(cvSEXP);
    Rcpp::traits::input_parameter< bool >::type thinoutputs(thinoutputsSEXP);
    __result = Rcpp::wrap(sbfc(TrainX, TrainY, TestX, TestY, nstep, thin, cv, thinoutputs));
    return __result;
END_RCPP
}
