// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP sbfc_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// sbfc
SEXP sbfc(SEXP TrainX, SEXP TrainY, SEXP TestX, SEXP TestY);
RcppExport SEXP sbfc_sbfc(SEXP TrainXSEXP, SEXP TrainYSEXP, SEXP TestXSEXP, SEXP TestYSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type TrainX(TrainXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TrainY(TrainYSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TestX(TestXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TestY(TestYSEXP);
    __result = Rcpp::wrap(sbfc(TrainX, TrainY, TestX, TestY));
    return __result;
END_RCPP
}
