# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sbfc_cpp <- function(TrainX = NULL, TrainY = NULL, TestX = NULL, TestY = NULL, nstep = NULL, thin = 50L, burnin_denom = 5L, cv = TRUE, thinoutputs = FALSE, alpha = 5, y_penalty = 1, x_penalty = 4) {
    .Call('_sbfc_sbfc_cpp', PACKAGE = 'sbfc', TrainX, TrainY, TestX, TestY, nstep, thin, burnin_denom, cv, thinoutputs, alpha, y_penalty, x_penalty)
}

